name: RT0902-IntroML
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs
  - jupyterlab
  - numpy>=1.18.1
  - h5py
  - holidays
  - scipy>=1.3.0
  - toolz
  - bokeh>=2.0.0
  - dask=2021.08.0
  - dask-labextension>=2.0.0
  - distributed
  - notebook
  - matplotlib
  - Pillow
  - pandas>=1.0.1
  - pandas-datareader
  - pytables
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - snakeviz
  - ujson
  - pip
  - s3fs
  - fastparquet
  - dask-ml
  - ipywidgets>=7.5
  - cachey
  - python-graphviz
  - zarr
  - scipy
  - seaborn
  - pyspark==3.2.3
  - scikit-learn
  - imageio
  - Pillow
  - joblib
  - tqdm
  - ipywidgets
  - jupyter-server-proxy
